// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { TraceId } from "./TraceId";

export type DomainEventDTO = { event: string, field_id: FieldId, change: string, revision: number, trace_id: TraceId, };
