// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { FieldMode } from "./FieldMode";

export type FieldSummary = { id: FieldId, title: string, goal: string | null, current_mode: FieldMode | null, current_focus: unknown | null, revision: number, updated_at: number, };
