// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { FieldLifecycle } from "./FieldLifecycle";
import type { FieldMode } from "./FieldMode";
import type { PrincipalId } from "./PrincipalId";

export type FieldView = { id: FieldId, owner_principal_id: PrincipalId, title: string, goal: string | null, lifecycle_status: FieldLifecycle, current_mode: FieldMode | null, current_focus: unknown | null, revision: number, created_at: number, updated_at: number, };
