// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";

export type FieldReferenceRequest = { field_id: FieldId, };
