// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreHealthState } from "./CoreHealthState";
import type { ProtocolVersion } from "./ProtocolVersion";

export type HealthDTO = { state: CoreHealthState, core_version: string, protocol: ProtocolVersion, schema_version: number, pid: number, db_path: string, };
