// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

export type HelloResponse = { core_version: string, protocol: ProtocolVersion, schema_version: number, capabilities: Array<string>, };
