// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";
import type { ObjectId } from "./ObjectId";

export type SaveSurfaceSnapshotRequest = { field_id: FieldId, layout: unknown, open_objects: Array<ObjectId>, };
