// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldView } from "./FieldView";
import type { SurfaceSnapshotView } from "./SurfaceSnapshotView";

export type SurfaceResumeView = { field: FieldView, snapshot: SurfaceSnapshotView | null, };
