// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "./DeviceId";
import type { FieldId } from "./FieldId";
import type { ObjectId } from "./ObjectId";
import type { SurfaceSnapshotId } from "./SurfaceSnapshotId";

export type SurfaceSnapshotView = { id: SurfaceSnapshotId, field_id: FieldId, device_id: DeviceId, observed_field_revision: number, layout: unknown, open_objects: Array<ObjectId>, created_at: number, };
