// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldId } from "./FieldId";

export type UpdateFocusRequest = { field_id: FieldId, expected_revision: number, focus: unknown, };
