export const channels = {
  projectPick: 'fielora:project:pick', projectList: 'fielora:project:list', projectGet: 'fielora:project:get', projectUpdate: 'fielora:project:update', projectArchive: 'fielora:project:archive', projectRebind: 'fielora:project:rebind',
  conversationCreate: 'fielora:conversation:create', conversationList: 'fielora:conversation:list', conversationGet: 'fielora:conversation:get',
  conversationUpdate: 'fielora:conversation:update', conversationArchive: 'fielora:conversation:archive',
  conversationMessageCreate: 'fielora:conversation:message:create', conversationMessageList: 'fielora:conversation:message:list',
  scheduledTaskList: 'fielora:scheduled-task:list', scheduledTaskCreate: 'fielora:scheduled-task:create',
  scheduledTaskUpdate: 'fielora:scheduled-task:update', scheduledTaskDelete: 'fielora:scheduled-task:delete', scheduledTaskRunNow: 'fielora:scheduled-task:run-now',
  artifactList: 'fielora:artifact:list', artifactRead: 'fielora:artifact:read', artifactHistory: 'fielora:artifact:history',
  artifactAssetPreview: 'fielora:artifact:asset-preview', artifactDiagramPreview: 'fielora:artifact:diagram-preview', artifactSetArchiveState: 'fielora:artifact:set-archive-state',
  artifactFileReviews: 'fielora:artifact:file-reviews', artifactFileMarkReviewed: 'fielora:artifact:file-mark-reviewed', artifactFileUndo: 'fielora:artifact:file-undo',
  workspaceFileList: 'fielora:workspace:file:list', workspaceFileRead: 'fielora:workspace:file:read', workspaceFilePreview: 'fielora:workspace:file:preview', workspaceFileApply: 'fielora:workspace:file:apply',
  workspaceEnvironment: 'fielora:workspace:environment',
  workspaceOpenTargets: 'fielora:workspace:open-targets', workspaceOpenProject: 'fielora:workspace:open-project',
  workspaceAttachmentPick: 'fielora:workspace:attachment:pick', workspaceAttachmentStore: 'fielora:workspace:attachment:store', workspaceAttachmentRead: 'fielora:workspace:attachment:read', workspaceAttachmentCopy: 'fielora:workspace:attachment:copy', workspaceAttachmentSave: 'fielora:workspace:attachment:save',
  workspaceTerminalRun: 'fielora:workspace:terminal:run', workspaceTerminalCancel: 'fielora:workspace:terminal:cancel', workspaceEvent: 'fielora:workspace:event',
  fieldCreate: 'fielora:field:create',
  fieldList: 'fielora:field:list',
  fieldGet: 'fielora:field:get',
  fieldUpdateFocus: 'fielora:field:update-focus',
  fieldUpdateMode: 'fielora:field:update-mode',
  fieldSetFocusV1: 'fielora:field:set-focus-v1',
  fieldResumeV1: 'fielora:field:resume-v1',
  stateCreate: 'fielora:state:create',
  stateGet: 'fielora:state:get',
  stateList: 'fielora:state:list',
  stateRevise: 'fielora:state:revise',
  stateTransition: 'fielora:state:transition',
  stateSupersede: 'fielora:state:supersede',
  referenceCreate: 'fielora:reference:create',
  referenceGet: 'fielora:reference:get',
  referenceList: 'fielora:reference:list',
  referenceRevise: 'fielora:reference:revise',
  referenceArchive: 'fielora:reference:archive',
  referenceRestore: 'fielora:reference:restore',
  relationAttachReferenceSource: 'fielora:relation:attach-reference-source',
  relationRetractReferenceSource: 'fielora:relation:retract-reference-source',
  relationList: 'fielora:relation:list',
  activityList: 'fielora:activity:list',
  surfaceSaveSnapshot: 'fielora:surface:save-snapshot',
  surfaceSaveSnapshotV1: 'fielora:surface:save-snapshot-v1',
  surfaceLatestSnapshot: 'fielora:surface:latest-snapshot',
  browserShow: 'fielora:browser:show',
  browserHide: 'fielora:browser:hide',
  browserCreatePage: 'fielora:browser:create-page',
  browserSwitchPage: 'fielora:browser:switch-page',
  browserClosePage: 'fielora:browser:close-page',
  browserShowPageContextMenu: 'fielora:browser:show-page-context-menu',
  browserNavigate: 'fielora:browser:navigate',
  browserBack: 'fielora:browser:back',
  browserForward: 'fielora:browser:forward',
  browserReload: 'fielora:browser:reload',
  browserState: 'fielora:browser:state',
  browserContext: 'fielora:browser:context',
  browserCaptureScreenshot: 'fielora:browser:capture-screenshot',
  screenshotGet: 'fielora:screenshot-evidence:get', screenshotByRun: 'fielora:screenshot-evidence:by-run', screenshotByVerification: 'fielora:screenshot-evidence:by-verification', screenshotPreview: 'fielora:screenshot-evidence:preview',
  clipboardWriteText: 'fielora:clipboard:write-text',
  windowTitlebarTheme: 'fielora:window:titlebar-theme',
  providerCreate: 'fielora:provider:create', providerUpdate: 'fielora:provider:update',
  providerStoreCredential: 'fielora:provider:store-credential', providerDeleteCredential: 'fielora:provider:delete-credential',
  providerRemove: 'fielora:provider:remove', providerProbe: 'fielora:provider:probe', providerList: 'fielora:provider:list', providerGet: 'fielora:provider:get',
  modelStart: 'fielora:model:start', modelCancel: 'fielora:model:cancel',
  agentStart: 'fielora:agent:start', agentGet: 'fielora:agent:get', agentList: 'fielora:agent:list',
  agentEvents: 'fielora:agent:events', agentToolCalls: 'fielora:agent:tool-calls',
  agentCancel: 'fielora:agent:cancel', agentPause: 'fielora:agent:pause', agentResume: 'fielora:agent:resume', agentResolveApproval: 'fielora:agent:resolve-approval',
  agentMcpConnections: 'fielora:agent:mcp-connections', agentMcpRuntime: 'fielora:agent:mcp-runtime', agentActivateMcpConnection: 'fielora:agent:activate-mcp-connection',
  agentSkillCatalog: 'fielora:agent:skill-catalog',
  pluginLocalRegistry: 'fielora:plugin:local-registry', pluginRegisterLocal: 'fielora:plugin:register-local', pluginUnregisterLocal: 'fielora:plugin:unregister-local',
  captureCreate: 'fielora:capture:create', captureAttach: 'fielora:capture:attach', capturePromote: 'fielora:capture:promote',
  captureArchive: 'fielora:capture:archive', captureRestore: 'fielora:capture:restore', captureList: 'fielora:capture:list', captureGet: 'fielora:capture:get',
  libraryAddFiles: 'fielora:library:add-files', librarySaveWeb: 'fielora:library:save-web', libraryList: 'fielora:library:list', libraryGet: 'fielora:library:get', libraryPreviewImage: 'fielora:library:preview-image', libraryDelete: 'fielora:library:delete', libraryOpen: 'fielora:library:open', libraryReveal: 'fielora:library:reveal',
  storageInfo: 'fielora:storage:info', storageOpen: 'fielora:storage:open', storageMigrateData: 'fielora:storage:migrate-data', storageMigrateLibrary: 'fielora:storage:migrate-library', storageClearCache: 'fielora:storage:clear-cache',
  profileGet: 'fielora:profile:get', profileExport: 'fielora:profile:export', profileImport: 'fielora:profile:import',
  browserEvent: 'fielora:browser:event',
  coreHealth: 'fielora:core:health',
  coreBuildProvenance: 'fielora:core:build-provenance',
  coreRetry: 'fielora:core:retry',
  coreOpenLogs: 'fielora:core:open-logs',
  coreQuit: 'fielora:core:quit',
  coreEvent: 'fielora:core:event',
  testKillCore: 'fielora:test:kill-core',
  testResizeWindow: 'fielora:test:resize-window',
  testCreateProject: 'fielora:test:create-project',
} as const;

export type InvokeChannel = Exclude<
  (typeof channels)[keyof typeof channels],
  typeof channels.coreEvent | typeof channels.browserEvent | typeof channels.workspaceEvent
>;
