export const channels = {
  fieldCreate: 'fielora:field:create',
  fieldList: 'fielora:field:list',
  fieldGet: 'fielora:field:get',
  fieldUpdateFocus: 'fielora:field:update-focus',
  fieldUpdateMode: 'fielora:field:update-mode',
  fieldSetFocusV1: 'fielora:field:set-focus-v1',
  fieldResumeV1: 'fielora:field:resume-v1',
  stateCreate: 'fielora:state:create',
  stateGet: 'fielora:state:get',
  stateList: 'fielora:state:list',
  stateRevise: 'fielora:state:revise',
  stateTransition: 'fielora:state:transition',
  stateSupersede: 'fielora:state:supersede',
  referenceCreate: 'fielora:reference:create',
  referenceGet: 'fielora:reference:get',
  referenceList: 'fielora:reference:list',
  referenceRevise: 'fielora:reference:revise',
  referenceArchive: 'fielora:reference:archive',
  referenceRestore: 'fielora:reference:restore',
  relationAttachReferenceSource: 'fielora:relation:attach-reference-source',
  relationRetractReferenceSource: 'fielora:relation:retract-reference-source',
  relationList: 'fielora:relation:list',
  activityList: 'fielora:activity:list',
  surfaceSaveSnapshot: 'fielora:surface:save-snapshot',
  surfaceSaveSnapshotV1: 'fielora:surface:save-snapshot-v1',
  surfaceLatestSnapshot: 'fielora:surface:latest-snapshot',
  coreHealth: 'fielora:core:health',
  coreRetry: 'fielora:core:retry',
  coreOpenLogs: 'fielora:core:open-logs',
  coreQuit: 'fielora:core:quit',
  coreEvent: 'fielora:core:event',
  testKillCore: 'fielora:test:kill-core',
} as const;

export type InvokeChannel = Exclude<(typeof channels)[keyof typeof channels], typeof channels.coreEvent>;
