[package]
name = "fielora-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fielora-contracts = { path = "../fielora-contracts" }
futures-util.workspace = true
reqwest.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

